[2023-09-17T19:43:38.700+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.data_preprocessing_task manual__2023-09-17T19:43:27.838009+00:00 [queued]>
[2023-09-17T19:43:38.730+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.data_preprocessing_task manual__2023-09-17T19:43:27.838009+00:00 [queued]>
[2023-09-17T19:43:38.732+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T19:43:38.734+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-17T19:43:38.735+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T19:43:38.785+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): data_preprocessing_task> on 2023-09-17 19:43:27.838009+00:00
[2023-09-17T19:43:38.803+0000] {standard_task_runner.py:55} INFO - Started process 5039 to run task
[2023-09-17T19:43:38.838+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'your_python_dag', 'data_preprocessing_task', 'manual__2023-09-17T19:43:27.838009+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp1sts6m9l']
[2023-09-17T19:43:38.854+0000] {standard_task_runner.py:83} INFO - Job 63: Subtask data_preprocessing_task
[2023-09-17T19:43:39.078+0000] {task_command.py:388} INFO - Running <TaskInstance: your_python_dag.data_preprocessing_task manual__2023-09-17T19:43:27.838009+00:00 [running]> on host 80c059a34b8e
[2023-09-17T19:43:39.390+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=your_python_dag
AIRFLOW_CTX_TASK_ID=data_preprocessing_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-17T19:43:27.838009+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-17T19:43:27.838009+00:00
[2023-09-17T19:43:39.392+0000] {logging_mixin.py:137} INFO - <class 'str'>
[2023-09-17T19:43:39.392+0000] {logging_mixin.py:137} INFO - ahbd
[2023-09-17T19:43:39.393+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/lab2.py", line 32, in data_preprocessing
    clustering_data = data[1, 3, 13]
TypeError: string indices must be integers
[2023-09-17T19:43:39.416+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=your_python_dag, task_id=data_preprocessing_task, execution_date=20230917T194327, start_date=20230917T194338, end_date=20230917T194339
[2023-09-17T19:43:39.431+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 63 for task data_preprocessing_task (string indices must be integers; 5039)
[2023-09-17T19:43:39.491+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-17T19:43:39.530+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
