[2023-10-01T03:34:45.386+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-01T03:34:36.552358+00:00 [queued]>
[2023-10-01T03:34:45.399+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-01T03:34:36.552358+00:00 [queued]>
[2023-10-01T03:34:45.399+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-10-01T03:34:45.399+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-10-01T03:34:45.400+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-10-01T03:34:45.411+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): build_save_model_task> on 2023-10-01 03:34:36.552358+00:00
[2023-10-01T03:34:45.419+0000] {standard_task_runner.py:55} INFO - Started process 2413 to run task
[2023-10-01T03:34:45.423+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Airflow-GitHub', 'build_save_model_task', 'manual__2023-10-01T03:34:36.552358+00:00', '--job-id', '317', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp1rwg8nh6']
[2023-10-01T03:34:45.425+0000] {standard_task_runner.py:83} INFO - Job 317: Subtask build_save_model_task
[2023-10-01T03:34:45.495+0000] {task_command.py:388} INFO - Running <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-01T03:34:36.552358+00:00 [running]> on host 434a62d4e45a
[2023-10-01T03:34:45.583+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dheeraj
AIRFLOW_CTX_DAG_ID=Airflow-GitHub
AIRFLOW_CTX_TASK_ID=build_save_model_task
AIRFLOW_CTX_EXECUTION_DATE=2023-10-01T03:34:36.552358+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-01T03:34:36.552358+00:00
[2023-10-01T03:34:45.720+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/joblib/parallel.py:1333: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  **self._backend_args)

[2023-10-01T03:34:45.720+0000] {logging_mixin.py:137} INFO - Fitting 10 folds for each of 64 candidates, totalling 640 fits
[2023-10-01T03:34:47.955+0000] {logging_mixin.py:137} INFO - Best parameters: {'C': 0.6, 'class_weight': {1: 0.5, 0: 0.5}, 'penalty': 'l2', 'solver': 'saga'}
[2023-10-01T03:34:47.964+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-10-01T03:34:47.980+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=Airflow-GitHub, task_id=build_save_model_task, execution_date=20231001T033436, start_date=20231001T033445, end_date=20231001T033447
[2023-10-01T03:34:48.034+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-10-01T03:34:48.071+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
